# Generated by Django 2.0 on 2020-10-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=125, verbose_name='登录密码')),
                ('profession', models.CharField(max_length=125, verbose_name='职业')),
                ('phone', models.CharField(max_length=128, verbose_name='电话')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
