# Generated by Django 3.1.1 on 2020-10-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(blank=True, max_length=255)),
                ('balance', models.IntegerField()),
                ('effectdate', models.DateField()),
                ('poscode', models.IntegerField()),
                ('toaccount', models.CharField(max_length=255)),
                ('tranamt', models.IntegerField()),
                ('exact_time', models.TimeField()),
            ],
            options={
                'db_table': 'CS_Consumption',
            },
        ),
    ]
