# Generated by Django 3.1.1 on 2020-10-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMealsCopy2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('term', models.CharField(blank=True, max_length=255, null=True)),
                ('breakfast_sum', models.FloatField(blank=True, null=True)),
                ('breakfast_aver', models.FloatField(blank=True, null=True)),
                ('breakfast_num', models.FloatField(blank=True, null=True)),
                ('lunch_sum', models.FloatField(blank=True, null=True)),
                ('lunch_aver', models.FloatField(blank=True, null=True)),
                ('lunch_num', models.FloatField(blank=True, null=True)),
                ('dinner_sum', models.FloatField(blank=True, null=True)),
                ('dinner_aver', models.FloatField(blank=True, null=True)),
                ('dinner_num', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'All_Meals_copy2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CS_All_Info',
            fields=[
                ('user_sno', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bksinfo_edm_xb', models.CharField(blank=True, db_column='BKSInfo_EDM_XB', max_length=10, null=True)),
                ('bksinfo_sfzh', models.CharField(blank=True, db_column='BKSInfo_SFZH', max_length=100, null=True)),
                ('bksinfo_edm_mz', models.CharField(blank=True, db_column='BKSInfo_EDM_MZ', max_length=200, null=True)),
                ('bksinfo_zymc', models.CharField(blank=True, db_column='BKSInfo_ZYMC', max_length=100, null=True)),
                ('bksinfo_xm', models.CharField(blank=True, db_column='BKSInfo_XM', max_length=100, null=True)),
                ('bksinfo_csrq', models.CharField(blank=True, db_column='BKSInfo_CSRQ', max_length=100, null=True)),
                ('bksinfo_edm_xy', models.CharField(blank=True, db_column='BKSInfo_EDM_XY', max_length=100, null=True)),
                ('bksinfo_jg', models.CharField(blank=True, db_column='BKSInfo_JG', max_length=200, null=True)),
                ('bksinfo_edm_zzmm', models.CharField(blank=True, db_column='BKSInfo_EDM_ZZMM', max_length=100, null=True)),
                ('personinfo_expdate', models.CharField(blank=True, db_column='PersonInfo_EXPDATE', max_length=50, null=True)),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('delete_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cs_all_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CS_Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=255)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('effectdate', models.DateField(blank=True, null=True)),
                ('poscode', models.IntegerField(blank=True, null=True)),
                ('toaccount', models.CharField(blank=True, max_length=255, null=True)),
                ('tranamt', models.IntegerField(blank=True, null=True)),
                ('exact_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cs_consumption',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Student_Consumption',
        ),
    ]
